#!/bin/bash

failure="artifacts/analysis/failure"

# if failure file not present, exit
if ! ls "$failure" &> /dev/null; then
  exit 0
fi

echo "~~~ :arrow_double_up: uploading failure analysis to s3"

PIPELINE_SLUG="${BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG:-BUILDKITE_PIPELINE_SLUG}"
BUILD_NUMBER="${BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER:-BUILDKITE_BUILD_NUMBER}"
aws s3 cp "$failure" "s3://uber-web-monorepo/analysis/${BUILDKITE_ORGANIZATION_SLUG}/${PIPELINE_SLUG}/build-${BUILD_NUMBER}/${BUILDKITE_JOB_ID}.failure"
