#!/bin/bash

set -eo pipefail

COMPOSE_FILE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_COMPOSE_FILE
IMAGE=$BUILDKITE_PLUGIN_DOCKER_CONTROL_IMAGE

if [ "$BUILDKITE_PLUGIN_DOCKER_CONTROL_LOGS" == "true" ]; then
echo "~~~ :docker: docker-control service logs" >&2
  docker-compose -f $COMPOSE_FILE logs --tail="all"
fi

# Try to spin down services
echo "~~~ :docker: docker-control cleanup" >&2
docker-compose -f $COMPOSE_FILE kill || true
docker-compose -f $COMPOSE_FILE down || true
echo "Removing image ${IMAGE}"
docker image rm "$IMAGE" || true
